language: en

pipeline:
- name: WhitespaceTokenizer
- name: LanguageModelFeaturizer
  model_name: "distilbert"
  model_weights: "distilbert-base-uncased"
- name: DIETClassifier
  epochs: 50
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 50
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3  
  core_fallback_action_name: "action_default_fallback"
- name: TEDPolicy
  max_history: 5
  epochs: 50

assistant_id: 20250816-181745-old-emerald
